2015-10-25 07:48:13,827 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 07:53:15,625 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 07:58:17,680 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:02:19,546 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:07:20,955 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:12:22,507 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:17:24,154 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:22:25,501 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:27:26,988 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:32:28,915 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:37:30,791 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:42:32,121 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:47:33,432 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:52:34,787 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 08:57:36,766 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:02:38,451 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:07:40,516 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:12:42,644 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:17:43,993 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:22:46,371 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:27:47,744 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:32:49,888 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:37:51,873 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:42:53,314 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:47:54,634 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:52:56,126 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 09:57:58,519 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:03:00,135 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:08:01,621 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:13:03,872 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:18:05,926 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:23:07,284 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:28:09,098 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:33:10,930 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:38:12,558 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:38:14,853 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-25 10:43:15,587 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:48:17,579 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:53:19,045 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 10:57:20,860 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:02:23,163 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:07:25,196 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:12:26,732 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:17:28,065 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:22:30,121 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:27:31,880 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:32:34,118 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:37:36,336 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:42:38,459 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:47:39,996 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:52:41,531 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 11:57:44,102 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:02:45,767 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:07:47,202 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:12:48,771 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:17:50,544 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:22:51,996 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:27:53,391 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:32:56,017 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:37:57,496 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:42:59,062 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:48:01,126 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:53:03,325 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 12:58:05,444 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:03:08,298 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:08:09,781 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:13:11,983 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:18:13,402 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:23:14,790 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:28:16,925 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:33:19,062 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:37:20,443 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:42:22,530 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:47:24,003 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:52:25,338 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 13:57:26,868 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:02:29,684 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:07:32,202 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:08:33,376 3011 INFO bitnami_openerp openerp.addons.google_calendar.google_calendar: Calendar Synchro - Started by cron
2015-10-25 14:08:33,376 3011 INFO bitnami_openerp openerp.addons.google_calendar.google_calendar: Calendar Synchro - Ended by cron
2015-10-25 14:12:33,597 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:17:35,263 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:22:37,283 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:27:39,086 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:32:40,558 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:37:42,740 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:42:44,621 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:47:45,965 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:52:47,702 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 14:57:49,422 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:02:51,239 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:07:52,749 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:12:54,512 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:17:55,961 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:22:57,620 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:27:58,985 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:33:00,939 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:38:02,368 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:43:03,983 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:48:05,729 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:53:07,904 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 15:58:09,553 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:03:11,830 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:08:13,983 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:13:16,080 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:18:17,859 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:22:19,848 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:27:21,251 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:32:22,921 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:37:25,058 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:42:27,241 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:47:30,004 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:52:32,255 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 16:57:33,701 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:02:35,514 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:07:36,957 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:12:38,381 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:17:40,390 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:22:41,936 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:27:44,238 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:32:45,813 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:37:47,336 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:42:48,745 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:47:50,755 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:52:52,789 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 17:57:55,249 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:02:57,007 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:07:58,886 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:13:01,034 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:18:03,063 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:23:05,182 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:28:06,987 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:33:08,720 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:38:10,200 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:43:11,625 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:48:13,125 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:53:14,646 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 18:58:16,067 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:03:17,962 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:07:19,442 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:12:20,783 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:17:22,368 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:22:24,537 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:27:26,098 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:32:27,839 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:33:33,491 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 19:33:33',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 19:33:33,491 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.1348 sec...
2015-10-25 19:35:14,790 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 19:35:14',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 19:35:14,791 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.4793 sec...
2015-10-25 19:37:29,405 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:42:21,461 3482 INFO bitnami_openerp openerp.service.common: successful login from 'raul.romero@emproltda.com' using database 'bitnami_openerp'
2015-10-25 19:42:30,849 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:47:32,410 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:52:33,901 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 19:57:35,479 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:02:37,755 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:07:39,601 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:12:41,740 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:17:43,527 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:22:45,573 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:27:47,692 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:32:50,022 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:37:51,429 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:42:53,546 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:47:55,545 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:52:57,652 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 20:58:00,200 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:03:02,656 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:08:04,132 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:13:06,618 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:18:08,242 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:23:10,373 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:28:11,793 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:33:14,143 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:38:15,638 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:43:17,187 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:47:19,187 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:52:20,389 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 21:57:21,813 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:02:23,645 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:07:25,842 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:12:27,339 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:17:28,686 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:22:30,741 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:27:33,184 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:32:34,882 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:37:36,681 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:39:17,830 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:39:17',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:39:17,831 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.5823 sec...
2015-10-25 22:40:59,511 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:40:59',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:40:59,511 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.5856 sec...
2015-10-25 22:42:38,780 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:43:32,154 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:43:32',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:43:32,155 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.9515 sec...
2015-10-25 22:45:13,919 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:45:13',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:45:13,919 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.2620 sec...
2015-10-25 22:47:40,927 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:47:45,619 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:47:45',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:47:45,619 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.3767 sec...
2015-10-25 22:49:33,952 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:49:33',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:49:33,956 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.6110 sec...
2015-10-25 22:51:19,336 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:51:19',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:51:19,337 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.7015 sec...
2015-10-25 22:52:11,570 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:52:11',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:52:11,571 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.5808 sec...
2015-10-25 22:52:42,202 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 22:53:04,849 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:53:04',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:53:04,849 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.1685 sec...
2015-10-25 22:54:46,280 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:54:46',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:54:46,281 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.0347 sec...
2015-10-25 22:55:36,537 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 22:55:36',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 22:55:36,537 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.4152 sec...
2015-10-25 22:57:44,065 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:02:45,806 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:07:48,096 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:12:49,405 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:17:51,517 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:22:53,121 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:27:55,132 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:32:33,143 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 23:32:33',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 23:32:33,143 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.5637 sec...
2015-10-25 23:32:33,143 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-25 23:32:33',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-25 23:32:33,144 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.3078 sec...
2015-10-25 23:32:56,713 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:37:58,698 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:43:00,196 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:48:01,772 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:53:03,878 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-25 23:58:05,713 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:03:07,496 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:08:09,073 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:13:11,190 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:18:16,361 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:23:18,566 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:27:19,980 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:32:21,756 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:37:23,257 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:42:24,856 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:47:26,249 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:52:27,814 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 00:57:29,178 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:02:31,232 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:07:32,852 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:12:34,431 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:17:36,138 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:22:37,560 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:27:39,133 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:32:42,349 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:37:44,507 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:42:45,925 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:47:48,012 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:52:50,232 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 01:57:51,681 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:02:54,300 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:07:55,865 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:08:57,338 3011 INFO bitnami_openerp openerp.addons.google_calendar.google_calendar: Calendar Synchro - Started by cron
2015-10-26 02:08:57,338 3011 INFO bitnami_openerp openerp.addons.google_calendar.google_calendar: Calendar Synchro - Ended by cron
2015-10-26 02:12:57,618 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:17:59,773 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:23:01,312 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:28:03,417 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:33:05,202 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:38:07,573 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:43:09,072 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:48:10,733 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:53:12,423 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 02:58:14,522 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:03:27,767 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:07:29,686 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:12:31,237 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:17:33,292 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:22:34,834 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:27:36,374 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:32:37,910 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:37:39,579 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:42:41,807 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:47:43,258 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:52:44,684 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 03:57:46,902 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:02:49,113 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:07:51,598 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:12:53,732 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:17:55,841 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:22:57,656 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:27:59,151 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:33:01,691 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:38:03,796 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:43:06,188 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:48:08,360 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:53:10,428 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 04:58:12,302 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:03:14,136 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:08:15,799 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:13:17,059 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:17:19,020 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:22:20,303 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:27:22,089 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:32:23,586 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:37:25,790 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:42:27,063 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:47:29,042 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:52:30,804 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 05:52:32,117 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 05:57:32,841 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:02:34,619 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:07:36,182 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:12:07,597 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 06:12:07',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 06:12:07,598 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.7768 sec...
2015-10-26 06:12:37,586 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:15:30,591 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 06:15:30',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 06:15:30,592 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.3438 sec...
2015-10-26 06:17:39,288 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:18:02,701 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 06:18:02',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 06:18:02,701 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.6365 sec...
2015-10-26 06:22:41,804 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:23:06,201 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 06:23:06',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 06:23:06,202 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.1973 sec...
2015-10-26 06:27:43,794 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:28:10,390 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 06:28:10',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 06:28:10,391 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.9797 sec...
2015-10-26 06:32:45,533 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:34:55,723 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 06:34:55',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 06:34:55,723 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.7564 sec...
2015-10-26 06:37:47,470 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:38:19,404 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 06:38:19',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 06:38:19,405 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.7956 sec...
2015-10-26 06:42:48,795 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:47:38,404 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 06:47:38',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 06:47:38,404 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.4344 sec...
2015-10-26 06:47:50,407 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:50:10,385 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 06:50:10',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 06:50:10,386 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.4293 sec...
2015-10-26 06:52:52,359 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 06:57:53,841 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:02:55,344 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:07:56,754 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:12:58,090 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:17:59,445 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:23:01,443 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:28:03,635 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:33:05,924 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:38:07,829 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:43:09,817 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:48:11,520 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:53:12,812 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:58:14,541 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 07:58:15,695 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 08:03:16,715 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:08:18,244 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:12:19,739 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:17:21,104 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:22:22,488 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:27:23,998 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:32:25,499 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:37:27,521 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:42:28,915 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:47:30,313 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:52:31,792 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 08:57:33,412 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:02:35,066 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:07:36,485 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:12:38,585 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:17:39,932 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:22:41,308 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:27:42,827 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:32:44,620 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:37:46,763 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:42:48,870 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:47:51,419 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:52:53,189 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 09:57:54,932 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:02:57,293 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:07:59,597 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:13:01,120 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:18:03,196 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:23:04,786 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:28:06,920 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:33:09,550 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:38:10,996 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:43:13,251 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:43:16,444 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 10:48:17,460 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:53:18,997 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 10:57:21,012 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:02:23,741 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:07:25,478 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:12:27,061 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:17:29,112 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:22:30,776 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:27:33,258 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:32:35,615 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:33:58,816 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 11:33:58',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 11:33:58,816 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.6967 sec...
2015-10-26 11:37:38,070 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:41:34,779 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 11:41:34',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 11:41:34,780 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.7611 sec...
2015-10-26 11:42:39,756 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:46:38,153 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 11:46:38',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 11:46:38,154 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.6204 sec...
2015-10-26 11:47:29,305 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 11:47:29',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 11:47:29,306 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.7193 sec...
2015-10-26 11:47:41,252 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:49:11,009 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 11:49:10',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 11:49:11,009 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.0032 sec...
2015-10-26 11:50:01,510 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 11:50:01',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 11:50:01,511 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.8666 sec...
2015-10-26 11:52:42,928 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:55:55,072 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 11:55:55',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 11:55:55,073 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.7412 sec...
2015-10-26 11:57:45,058 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 11:58:27,034 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 11:58:27',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 11:58:27,034 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.1278 sec...
2015-10-26 12:02:47,381 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:07:48,940 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:12:51,164 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:17:53,259 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:22:55,492 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:27:56,956 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:32:58,656 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:38:00,512 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:43:01,921 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:48:04,007 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:53:05,760 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 12:58:07,256 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:03:09,243 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:08:10,681 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:08:11,821 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 13:13:12,581 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:13:38,235 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 13:13:38',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 13:13:38,235 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.4454 sec...
2015-10-26 13:15:20,007 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 13:15:19',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 13:15:20,008 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.6520 sec...
2015-10-26 13:18:14,159 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:18:16,147 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 13:21:00,577 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 13:21:00',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 13:21:00,578 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.6830 sec...
2015-10-26 13:23:16,887 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:23:18,139 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 13:27:19,038 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:32:20,550 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:37:22,042 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:42:23,476 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:47:25,121 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:52:27,249 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 13:52:29,271 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 13:57:30,053 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:02:32,176 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:07:33,884 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:08:35,208 3011 INFO bitnami_openerp openerp.addons.google_calendar.google_calendar: Calendar Synchro - Started by cron
2015-10-26 14:08:35,209 3011 INFO bitnami_openerp openerp.addons.google_calendar.google_calendar: Calendar Synchro - Ended by cron
2015-10-26 14:12:35,507 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:17:37,058 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:22:39,190 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:22:40,363 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 14:27:41,591 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:32:43,627 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:37:45,118 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:42:46,754 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:47:48,361 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:49:16,435 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 14:49:16',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 14:49:16,436 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.6203 sec...
2015-10-26 14:52:49,737 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 14:57:51,827 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:02:54,485 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:07:56,025 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:12:57,580 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:17:59,041 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:18:00,315 3011 INFO bitnami_openerp openerp.addons.mail.mail_thread: Routing mail from Raul Romero <raul.romero@emproltda.com> to Juan Pablo Romero <jpromero@emproltda.com> with Message-Id <CAKLcJE9jEObOij=yJbtstwF_9+LCZWHatvCoh0jGu0fPN6iYbQ@mail.gmail.com>: direct alias match: (u'res.users', 14, {}, 5, mail.alias(25,))
2015-10-26 15:18:01,267 3011 INFO bitnami_openerp openerp.addons.mail.mail_mail: Mail with ID 58 and Message-Id u'<CAKLcJE9jEObOij=yJbtstwF_9+LCZWHatvCoh0jGu0fPN6iYbQ@mail.gmail.com>' successfully sent
2015-10-26 15:23:02,476 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:28:04,880 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:28:21,067 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 15:28:21',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 15:28:21,068 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.3436 sec...
2015-10-26 15:30:53,210 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 15:30:53',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 15:30:53,211 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.9083 sec...
2015-10-26 15:33:07,327 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:38:08,966 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:43:10,391 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:48:12,547 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:53:14,552 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:55:26,771 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 15:55:26',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 15:55:26,772 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.4204 sec...
2015-10-26 15:58:16,063 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 15:58:48,792 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 15:58:48',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 15:58:48,792 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.3025 sec...
2015-10-26 16:02:10,631 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 16:02:10',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 16:02:10,636 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.4985 sec...
2015-10-26 16:03:17,936 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:05:32,695 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 16:05:32',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 16:05:32,696 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.2042 sec...
2015-10-26 16:07:13,691 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 16:07:13',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 16:07:13,692 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.8773 sec...
2015-10-26 16:07:20,001 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:11:26,472 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 16:11:26',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 16:11:26,473 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.1871 sec...
2015-10-26 16:12:21,440 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:17:22,849 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:22:24,944 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:27:26,655 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:28:26,935 3034 ERROR bitnami_openerp openerp.sql_db: bad query: UPDATE "im_chat_presence" SET "status"='away',"last_poll"='2015-10-26 16:28:26',"write_uid"=20,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
TransactionRollbackError: could not serialize access due to concurrent update

2015-10-26 16:28:26,935 3034 INFO bitnami_openerp openerp.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.2387 sec...
2015-10-26 16:32:28,465 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:37:30,056 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:42:32,269 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:47:33,900 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:52:35,804 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 16:57:37,310 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:02:39,162 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:07:41,011 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:12:43,062 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:17:44,651 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:22:46,680 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:27:48,122 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:32:50,453 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:37:52,108 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:42:53,742 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:47:55,126 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:52:56,860 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 17:57:59,022 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:03:08,751 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:08:10,683 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:13:12,714 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:18:14,551 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:23:16,060 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:27:19,530 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:32:21,238 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:37:22,659 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:42:24,264 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:47:25,899 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:52:27,492 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 18:57:29,058 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:02:30,810 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:07:32,297 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:12:34,465 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:17:35,961 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:22:37,374 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:27:39,062 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:32:40,800 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:37:42,423 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:42:43,874 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:47:45,411 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:52:46,727 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 19:57:49,188 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:02:51,155 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:07:48,679 3481 ERROR bitnami_openerp openerp.sql_db: bad query: INSERT INTO "res_users" ("id", "partner_id", "alias_id", "default_section_id", "share", "active", "oauth_access_token", "signature", "oauth_uid", "company_id", "action_id", "google_calendar_token_validity", "oauth_provider_id", "display_employees_suggestions", "google_calendar_rtoken", "password", "login", "google_calendar_last_sync_date", "display_groups_suggestions", "google_calendar_token", "google_calendar_cal_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_users_id_seq'), 33, 37, NULL, false, true, 'ya29.GAITcoV9KQTO_njxnmUW1NA3-kkmtjPivSGyGXZKUwebLDaRC3_2JL-D4SvluJbi9CgX', NULL, '110566688986281923024', 1, NULL, '2015-09-10 22:48:20', 3, true, NULL, '', 'byanez@emproltda.com', NULL, true, NULL, NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "res_users_login_key"
DETAIL:  Key (login)=(byanez@emproltda.com) already exists.

2015-10-26 20:07:48,741 3481 INFO bitnami_openerp openerp.addons.auth_oauth.controllers.main: OAuth2: access denied, redirect to main page in case a valid session exists, without setting cookies
2015-10-26 20:07:52,555 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:08:20,023 3482 ERROR bitnami_openerp openerp.sql_db: bad query: INSERT INTO "res_users" ("id", "partner_id", "alias_id", "default_section_id", "share", "active", "oauth_access_token", "signature", "oauth_uid", "company_id", "action_id", "google_calendar_token_validity", "oauth_provider_id", "display_employees_suggestions", "google_calendar_rtoken", "password", "login", "google_calendar_last_sync_date", "display_groups_suggestions", "google_calendar_token", "google_calendar_cal_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_users_id_seq'), 34, 38, NULL, false, true, 'ya29.GAJLq-AFBfNYkN-X1DJ_MqWf1MhPnUTmnpTC5dV1uxwOPUzn0Eek5-UIoQizbDdZcFsH', NULL, '110566688986281923024', 1, NULL, '2015-09-10 22:48:20', 3, true, NULL, '', 'byanez@emproltda.com', NULL, true, NULL, NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "res_users_login_key"
DETAIL:  Key (login)=(byanez@emproltda.com) already exists.

2015-10-26 20:08:20,024 3482 INFO bitnami_openerp openerp.addons.auth_oauth.controllers.main: OAuth2: access denied, redirect to main page in case a valid session exists, without setting cookies
2015-10-26 20:08:29,726 3481 ERROR bitnami_openerp openerp.sql_db: bad query: INSERT INTO "res_users" ("id", "partner_id", "alias_id", "default_section_id", "share", "active", "oauth_access_token", "signature", "oauth_uid", "company_id", "action_id", "google_calendar_token_validity", "oauth_provider_id", "display_employees_suggestions", "google_calendar_rtoken", "password", "login", "google_calendar_last_sync_date", "display_groups_suggestions", "google_calendar_token", "google_calendar_cal_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('res_users_id_seq'), 35, 39, NULL, false, true, 'ya29.GAKMcvDV6vxVtdOgYwPdQh_hpn1_0O2xB9FYbGbXY8K30XZS01W4QLt-wLunOhpr1YEk', NULL, '110566688986281923024', 1, NULL, '2015-09-10 22:48:20', 3, true, NULL, '', 'byanez@emproltda.com', NULL, true, NULL, NULL, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "res_users_login_key"
DETAIL:  Key (login)=(byanez@emproltda.com) already exists.

2015-10-26 20:08:29,727 3481 INFO bitnami_openerp openerp.addons.auth_oauth.controllers.main: OAuth2: access denied, redirect to main page in case a valid session exists, without setting cookies
2015-10-26 20:09:14,335 3482 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:09:14,532 3481 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:09:30,086 3481 INFO bitnami_openerp openerp.service.common: successful login from 'raul.romero@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:09:32,829 3481 INFO bitnami_openerp openerp.addons.base.res.res_users: Login failed for db:bitnami_openerp login:webmaster@emproltda.com
2015-10-26 20:09:50,805 3481 INFO bitnami_openerp openerp.service.common: successful login from 'webmaster@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:12:11,107 3481 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:12:11,349 3482 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:12:23,798 3481 INFO bitnami_openerp openerp.service.common: successful login from 'byanez@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:12:54,455 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:12:55,677 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 20:13:22,719 3482 WARNING bitnami_openerp openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 27, model: hr.payslip
2015-10-26 20:13:22,720 3482 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3125, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3160, in read
    self._read_from_database(stored, inherited)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3338, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/osv/fields.py", line 1448, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/hr_payroll/hr_payroll.py", line 969, in _payslip_count
    for employee_id in ids
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/hr_payroll/hr_payroll.py", line 969, in <dictcomp>
    for employee_id in ids
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 1618, in search_count
    res = self.search(cr, user, args, context=context, count=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 1639, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 4615, in _search
    self.check_access_rights(cr, access_rights_uid or user, 'read')
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3477, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in check
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 800, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Lo siento, no est\xe1 autorizado para acceder a este documento. S\xf3lo usuarios con los siguientes permisos est\xe1n autorizados a hacer esto:\n- Human Resources/Officer\n\n(Modelo de documento: hr.payslip)')
2015-10-26 20:13:35,228 3482 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 1246, in run
    [action_id], request.context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_actions.py", line 1002, in run
    res = func(cr, uid, action, eval_context=eval_context, context=run_context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/website/models/ir_actions.py", line 62, in run_action_code_multi
    res = super(actions_server, self).run_action_code_multi(cr, uid, action, eval_context, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_actions.py", line 836, in run_action_code_multi
    eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/hr_timesheet_sheet/wizard/hr_timesheet_current.py", line 38, in open_timesheet
    raise osv.except_osv(_('Error!'), _('Please create an employee and associate it with this user.'))
except_orm: (u'\xa1Error!', u'Por favor, cree un empleado y as\xf3cielo con este usuario.')
2015-10-26 20:15:36,405 3482 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:15:36,749 3481 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:15:44,003 3481 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:15:44,291 3482 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:15:50,071 3481 INFO bitnami_openerp openerp.service.common: successful login from 'byanez@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:16:54,837 3482 WARNING bitnami_openerp openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: write, uid: 27, model: res.users
2015-10-26 20:16:54,837 3482 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/res_users.py", line 172, in write
    write_res = super(res_users_mail_group, self).write(cr, uid, ids, vals, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/res/res_users.py", line 824, in write
    return super(users_view, self).write(cr, uid, ids, values, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/res/res_users.py", line 649, in write
    super(users_implied, self).write(cr, uid, [user.id], vals, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/res/res_users.py", line 331, in write
    res = super(res_users, self).write(cr, uid, ids, values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3737, in write
    self.check_access_rights('write')
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 441, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3477, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in check
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 800, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Lo siento, no est\xe1 autorizado para modificar este documento. S\xf3lo usuarios con los siguientes permisos est\xe1n autorizados a hacer esto:\n- Administration/Access Rights\n\n(Modelo de documento: res.users)')
2015-10-26 20:16:55,099 3482 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:17:07,891 3481 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:17:11,708 3481 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:17:12,009 3482 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:17:56,337 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:19:21,181 3482 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:19:21,511 3481 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:19:49,893 3481 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:19:50,125 3482 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:19:50,380 3482 WARNING bitnami_openerp openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 28, model: ir.ui.menu
2015-10-26 20:20:00,909 3482 WARNING bitnami_openerp openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 28, model: ir.ui.menu
2015-10-26 20:20:39,207 3481 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:20:39,514 3482 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:20:48,932 3482 INFO bitnami_openerp openerp.service.common: successful login from 'byanez@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:21:08,146 3482 WARNING bitnami_openerp openerp.addons.base.ir.ir_model: Access Denied by ACLs for operation: read, uid: 28, model: hr.payslip
2015-10-26 20:21:08,146 3482 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 936, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3125, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3160, in read
    self._read_from_database(stored, inherited)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3338, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/osv/fields.py", line 1448, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/hr_payroll/hr_payroll.py", line 969, in _payslip_count
    for employee_id in ids
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/hr_payroll/hr_payroll.py", line 969, in <dictcomp>
    for employee_id in ids
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 1618, in search_count
    res = self.search(cr, user, args, context=context, count=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 1639, in search
    return self._search(cr, user, args, offset=offset, limit=limit, order=order, context=context, count=count)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 4615, in _search
    self.check_access_rights(cr, access_rights_uid or user, 'read')
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/models.py", line 3477, in check_access_rights
    return self.pool.get('ir.model.access').check(cr, uid, self._name, operation, raise_exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "<string>", line 2, in check
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/cache.py", line 122, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 800, in check
    raise openerp.exceptions.AccessError(msg % msg_params)
AccessError: ('AccessError', u'Lo siento, no est\xe1 autorizado para acceder a este documento. S\xf3lo usuarios con los siguientes permisos est\xe1n autorizados a hacer esto:\n- Human Resources/Officer\n\n(Modelo de documento: hr.payslip)')
2015-10-26 20:22:57,917 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:25:51,411 3481 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:25:51,731 3482 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:25:53,157 3481 WARNING bitnami_openerp openerp.addons.base.res.res_font: Could not register Font /usr/share/fonts/truetype/ttf-indic-fonts-core/Vemana.ttf: Font does not allow subsetting/embedding (0002)
2015-10-26 20:25:53,171 3481 WARNING bitnami_openerp openerp.addons.base.res.res_font: Could not register Font /usr/share/fonts/truetype/ttf-indic-fonts-core/Pothana2000.ttf: Font does not allow subsetting/embedding (0002)
2015-10-26 20:25:58,694 3481 WARNING bitnami_openerp openerp.addons.base.res.res_font: Could not register Font /usr/share/fonts/truetype/droid/DroidSansJapanese.ttf: Font does not have cmap for Unicode (platform 3, encoding 1, format 4 or platform 0 any encoding format 4)
2015-10-26 20:27:59,996 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:28:24,275 3482 INFO bitnami_openerp openerp.addons.base.res.res_config: getting next operation
2015-10-26 20:28:24,276 3482 INFO bitnami_openerp openerp.addons.base.res.res_config: getting next ir.actions.todo
2015-10-26 20:28:24,314 3482 INFO bitnami_openerp openerp.addons.base.res.res_config: next action is None
2015-10-26 20:28:24,315 3482 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:28:24,621 3481 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:28:31,828 3481 INFO bitnami_openerp openerp.service.common: successful login from 'raul.romero@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:28:42,500 3482 INFO bitnami_openerp openerp.service.common: successful login from 'byanez@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:29:29,750 3482 INFO bitnami_openerp openerp.addons.auth_oauth.controllers.main: OAuth2: access denied, redirect to main page in case a valid session exists, without setting cookies
2015-10-26 20:31:06,046 3482 INFO bitnami_openerp openerp.addons.mail.mail_mail: Mail with ID 60 and Message-Id u'<1445891465.253602027893066.345945001413740-openerp-29-res.users@bitnami-odoo-1e16>' successfully sent
2015-10-26 20:31:06,096 3482 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:31:06,382 3481 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:31:44,786 3482 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:31:45,068 3481 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:31:50,683 3482 INFO bitnami_openerp openerp.service.common: successful login from 'byanez@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:32:11,562 3482 INFO bitnami_openerp openerp.modules.registry: At least one model cache has been cleared, signaling through the database.
2015-10-26 20:32:11,780 3481 INFO bitnami_openerp openerp.modules.registry: Invalidating all model caches after database signaling.
2015-10-26 20:32:16,937 3482 INFO bitnami_openerp openerp.service.common: successful login from 'byanez@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:33:02,397 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:33:04,797 3011 INFO bitnami_openerp openerp.addons.mail.mail_mail: Mail with ID 59 and Message-Id u'<1444927440.652915000915527.401053821452308-openerp-10-hr.employee@bitnami-odoo-1e16>' successfully sent
2015-10-26 20:34:01,625 3482 INFO bitnami_openerp openerp.service.common: successful login from 'raul.romero@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:38:05,085 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:38:27,894 3011 INFO bitnami_openerp openerp.addons.mail.mail_thread: Routing mail from Raul Romero <raul.romero@emproltda.com> to aromero@emproltda.com, jpromero@emproltda.com, Byanez@emproltda.com with Message-Id <CAKLcJE-FjN79U1W3T+2gUy-y6s6ir_hH6ZQziD7=Lx7w8GG2Pw@mail.gmail.com>: direct alias match: (u'res.users', 14, {}, 5, mail.alias(25,))
2015-10-26 20:38:28,487 3011 INFO bitnami_openerp openerp.addons.mail.mail_mail: Mail with ID 61 and Message-Id u'<CAKLcJE-FjN79U1W3T+2gUy-y6s6ir_hH6ZQziD7=Lx7w8GG2Pw@mail.gmail.com>' successfully sent
2015-10-26 20:38:28,973 3011 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to process mail from pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 239, in fetch_mail
    context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1183, in message_process
    routes = self.message_route(cr, uid, msg_txt, msg, model, thread_id, custom_values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 1068, in message_route
    update_author=True, assert_model=True, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/mail/mail_thread.py", line 837, in message_route_verify
    raise ValueError('Routing: posting a message without model should be with a parent_id (private mesage).')
ValueError: Routing: posting a message without model should be with a parent_id (private mesage).
2015-10-26 20:39:49,066 3481 INFO bitnami_openerp openerp.service.common: successful login from 'raul.romero@emproltda.com' using database 'bitnami_openerp'
2015-10-26 20:41:19,612 3482 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 1246, in run
    [action_id], request.context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 900, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_actions.py", line 1002, in run
    res = func(cr, uid, action, eval_context=eval_context, context=run_context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/website/models/ir_actions.py", line 62, in run_action_code_multi
    res = super(actions_server, self).run_action_code_multi(cr, uid, action, eval_context, context)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_actions.py", line 836, in run_action_code_multi
    eval(action.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/hr_timesheet_sheet/wizard/hr_timesheet_current.py", line 38, in open_timesheet
    raise osv.except_osv(_('Error!'), _('Please create an employee and associate it with this user.'))
except_orm: (u'\xa1Error!', u'Por favor, cree un empleado y as\xf3cielo con este usuario.')
2015-10-26 20:42:29,698 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:46:23,258 3481 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_mail_server.py", line 215, in test_smtp_connection
    raise osv.except_osv(_("Connection Test Succeeded!"), _("Everything seems properly set up!"))
except_orm: (u'\xa1Prueba de conexi\xf3n realizada con \xe9xito!', u'\xa1Todo parece correctamente configurado!')
2015-10-26 20:46:46,852 3481 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_mail_server.py", line 215, in test_smtp_connection
    raise osv.except_osv(_("Connection Test Succeeded!"), _("Everything seems properly set up!"))
except_orm: (u'\xa1Prueba de conexi\xf3n realizada con \xe9xito!', u'\xa1Todo parece correctamente configurado!')
2015-10-26 20:47:03,855 3482 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_mail_server.py", line 208, in test_smtp_connection
    raise osv.except_osv(_("Connection Test Failed!"), _("Here is what we got instead:\n %s") % tools.ustr(e))
except_orm: (u'\xa1Test de conexi\xf3n fallido!', u'Esto es lo que hay en su lugar:\n SMTP AUTH extension not supported by server.')
2015-10-26 20:47:09,506 3481 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_mail_server.py", line 215, in test_smtp_connection
    raise osv.except_osv(_("Connection Test Succeeded!"), _("Everything seems properly set up!"))
except_orm: (u'\xa1Prueba de conexi\xf3n realizada con \xe9xito!', u'\xa1Todo parece correctamente configurado!')
2015-10-26 20:47:25,021 3481 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_mail_server.py", line 208, in test_smtp_connection
    raise osv.except_osv(_("Connection Test Failed!"), _("Here is what we got instead:\n %s") % tools.ustr(e))
except_orm: (u'\xa1Test de conexi\xf3n fallido!', u'Esto es lo que hay en su lugar:\n 535\n5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/answer/14257 h22sm3670195qge.43 - gsmtp')
2015-10-26 20:47:31,227 3011 INFO bitnami_openerp openerp.addons.fetchmail.fetchmail: start checking for new emails on pop server Raul Pop
2015-10-26 20:48:25,392 3481 ERROR bitnami_openerp openerp.addons.fetchmail.fetchmail: Failed to connect to pop server Raul Pop.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 160, in button_confirm_login
    connection = server.connect()
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 546, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 152, in connect
    connection.pass_(server.password)
  File "/opt/bitnami/python/lib/python2.7/poplib.py", line 197, in pass_
    return self._shortcmd('PASS %s' % pswd)
  File "/opt/bitnami/python/lib/python2.7/poplib.py", line 160, in _shortcmd
    return self._getresp()
  File "/opt/bitnami/python/lib/python2.7/poplib.py", line 136, in _getresp
    raise error_proto(resp)
error_proto: -ERR [AUTH] Username and password not accepted.
2015-10-26 20:48:25,428 3481 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/fetchmail/fetchmail.py", line 164, in button_confirm_login
    raise osv.except_osv(_("Connection test failed!"), _("Here is what we got instead:\n %s.") % tools.ustr(e))
except_orm: (u'\xa1Ha fallado el test de conexi\xf3n!', u'Esto es lo que se obtuvo en su lugar:\n -ERR [AUTH] Username and password not accepted..')
2015-10-26 20:50:20,828 3482 ERROR bitnami_openerp openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-8.0_20150423-py2.7.egg/openerp/addons/base/ir/ir_mail_server.py", line 215, in test_smtp_connection
    raise osv.except_osv(_("Connection Test Succeeded!"), _("Everything seems properly set up!"))
except_orm: (u'\xa1Prueba de conexi\xf3n realizada con \xe9xito!', u'\xa1Todo parece correctamente configurado!')
2015-10-26 20:50:43,988 3481 INFO bitnami_openerp openerp.addons.mail.mail_mail: Mail with ID 63 and Message-Id u'<1445892643.391088962554932.555341062509942-openerp-20-res.users@bitnami-odoo-1e16>' successfully sent
2015-10-27 02:08:53,664 3011 INFO bitnami_openerp openerp.addons.google_calendar.google_calendar: Calendar Synchro - Started by cron
2015-10-27 02:08:53,673 3011 INFO bitnami_openerp openerp.addons.google_calendar.google_calendar: Calendar Synchro - Ended by cron
